version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Install AWS CLI and build JAR
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip
            sudo pip3 install awscli
            echo "AWS VERSION"
            aws --version
            mvn clean install

      - run:
          name: Upload ZIP to S3
          command: |
            pwd
            cd target/
            ls -al
            aws s3 cp faas-1.0-SNAPSHOT.jar s3://lambda.ankitpatro.me

      - run:
          name: Create Deployment
          command: aws lambda update-function-code --region us-east-1 --function-name func_lambda --s3-bucket lambda.ankitpatro.me --s3-key faas-1.0-SNAPSHOT.jar



workflows:
  version: 2
  build_deploy:
    jobs:
      - build
#          filters:
#            branches:
#              only: master





